import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import request from '../utils/request'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
        <Header/>


      {/* Navbar */}
      <Nav/>


      
      {/* Results */}
      <Results/>
    </div>
  )
}
//render in the server first
 //export async function getServerSideProps(context){
   //const genre = context.query.genre;

//    const request = await fetch(`https://api.themoviedb.org/3${request[genre]}`)

 //}